# baseURL = "https://demo.gethugothemes.com/timer/site/"
languageCode = "en-us"
title = "Prakriti"
theme = "timer-hugo"
# post pagination
paginate = "2" # see https://gohugo.io/extras/pagination/
baseURL = "http://localhost:1313/"
# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
[[menu.main]]
name = "Home"
url = "#"
weight = 1

[[menu.main]]
name = "About"
# url = "about/"
url = "#about"
weight = 2

[[menu.main]]
name = "Team"
url = "#team"
weight = 3

[[menu.main]]
name = "Projects"
url = "/portfolio"
weight = 4

[[menu.main]]
name = "Blog"
url = "blog/"
weight = 5

[[menu.main]]
name = "Contact"
url = "#call-to-action"
weight = 6

# Site Params
[params]
home = "Home"
logo = "images/logo.png"
dateFormat = "6 January 2006"
# Meta data
description = "Timer Hugo theme"
author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "Your ID"
# contact form action
contactFormAction = "#" # contact form works with https://formspree.io

# Banner Section
[params.banner]
enable = true
bgImage = "images/slider.jpg"
heading = "Prakriti is the club for "
description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation"
# button
btn = true
btnText = "Explore"
btnURL = "https://themefisher.com/"

# flip text
[[params.banner.flipText]]
title = "NATURE"
[[params.banner.flipText]]
title = "PLANTS"
[[params.banner.flipText]]
title = "TREES"

# Homepage About Section
[params.about]
enable = true
title = "ABOUT PRAKRITI"
content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation<br> <br> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, adipisci voluptatum repudiandae, natus impedit repellat aut officia illum at assumenda iusto reiciendis placeat. Temporibus, vero."
image = "images/about/about.jpg"

# Homepage Teams Section
[params.team]
enable = true
title = "The Team"

# Call to Action
[params.cta]
enable = true
title = "SO WHAT YOU THINK ?"
content = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis,<br>possimus commodi, fugiat magnam temporibus vero magni recusandae? Dolore, maxime praesentium."
btnText = "Contact with me"
btnURL = "/contact"

# Portfolio Section On Homepage
[params.portfolio]
enable = true
title = "Latest Projects"
subtitle = "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

# social icon
[[params.socialIcon]]
icon = "ion-social-facebook"
url = "#"

[[params.socialIcon]]
icon = "ion-social-instagram"
url = "#"

[[params.socialIcon]]
icon = "ion-social-linkedin"
url = "#"
